#!/usr/bin/env python3
"""Print the build plugins as PURLs, one per line.

tools/pom.xml and tools/build.gradle exist to pin versions where Dependabot
can maintain them. They are not projects: the pom declares no dependencies and
the gradle file is a bare buildscript block, so asking a generator to resolve
either produces nothing. cdxgen fails outright, with "null null".

The plugins are still part of the supply chain -- Maven, Gradle and sbt fetch
them at run time and they shape every JVM SBOM we produce -- but they appear in
no artifact we ship, which is exactly what additional packages are for. This
emits them in the format ADDITIONAL_PACKAGES_FILE expects, read from the same
manifests Dependabot updates, so the SBOM cannot drift from the pins.

    python scripts/plugin_purls.py > additional_packages.txt
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

#: (manifest, how to find it, the PURL it becomes).
#:
#: sbt-sbom carries sbt's cross-version suffix in its artifactId, which is how
#: Maven Central publishes it, so the PURL keeps it verbatim rather than
#: inventing a cleaner name that resolves to nothing.
PLUGINS = [
    ("tools/pom.xml", "org.cyclonedx", "cyclonedx-maven-plugin"),
    ("tools/pom.xml", "com.github.sbt", "sbt-sbom_2.12_1.0"),
    ("tools/build.gradle", "org.cyclonedx", "cyclonedx-gradle-plugin"),
]


def version_of(manifest: str, group: str, artifact: str) -> str:
    text = (ROOT / manifest).read_text()
    if manifest.endswith(".xml"):
        match = re.search(
            rf"<artifactId>{re.escape(artifact)}</artifactId>\s*<version>([^<]+)</version>",
            text,
        )
    else:
        match = re.search(rf"{re.escape(group)}:{re.escape(artifact)}:([0-9][^\"'\s]*)", text)
    if not match:
        raise SystemExit(f"error: {group}:{artifact} not found in {manifest}")
    return match.group(1).strip()


def main() -> int:
    print("# Generated by scripts/plugin_purls.py -- do not edit.")
    print("# The CycloneDX build plugins, fetched at run time by the user's own")
    print("# Maven, Gradle or sbt and present in no artifact we ship.")
    for manifest, group, artifact in PLUGINS:
        print(f"pkg:maven/{group}/{artifact}@{version_of(manifest, group, artifact)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
